//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public Books()
        {
            this.BookRentHistories = new HashSet<BookRentHistory>();
        }
    
        public int Id { get; set; }
        public string ISBN { get; set; }
        public string BookName { get; set; }
        public byte[] Cover { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public int ModifiedBy { get; set; }
        public short Status { get; set; }
        public System.DateTime LastRentOn { get; set; }
    
        public virtual ICollection<BookRentHistory> BookRentHistories { get; set; }
    }
}
