//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookRentHistory
    {
        public int Id { get; set; }
        public string ISBN { get; set; }
        public int UserId { get; set; }
        public System.DateTime RentOn { get; set; }
        public System.DateTime ReturnedOn { get; set; }
    
        public virtual LibraryUsers LibraryUser { get; set; }
        public virtual Books Book { get; set; }
    }
}
