//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryUsers
    {
        public LibraryUsers()
        {
            this.BookRentHistories = new HashSet<BookRentHistory>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string UserRole { get; set; }
        public short Status { get; set; }
    
        public virtual ICollection<BookRentHistory> BookRentHistories { get; set; }
    }
}
