//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleLibrary.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SimpLibSysContainer : DbContext
    {
        public SimpLibSysContainer()
            : base("name=SimpLibSysContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LibraryUsers> LibraryUsers { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<BookRentHistory> BookRentHistories { get; set; }
    }
}
